services:
  - type: web
    name: movie-flask
    env: python
    workingDirectory: /opt/render/project  # Use root
    buildCommand: |
      pip install -r requirements.txt
      g++ -std=c++17 main.cpp -o program
      chmod +x program
      ls -l
      echo "Build complete!"
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
