services:
  - type: web
    name: movie-flask
    env: python
    buildCommand: |
      pip install -r requirements.txt
      g++ -std=c++17 main.cpp -o program
      chmod +x program
    startCommand: python server.py